[[intro_chapter]]
== 이더리움 베이직

((("Ethereum (generally)","basics", id="ix_02intro-asciidoc0", range="startofrange"))) 이번 챕터에서는 이더리움에 대해서 본격적으로 알아볼 것이고, 지갑을 어떻게 사용하는지, 거래(트랜잭션)는 어떻게 발생시키는지 그리고 기본적인 스마트 컨트랙트를 어떻게 작동시키는지에 대해서 배울 것이다.

[[ether_units]]
=== 이더리움 화폐 단위

((("currency units")))((("Ethereum (generally)","currency units")))이더리움의 화폐 단위는 _이더(ether)_  라고 불리운다. 또한 "ETH"라고 혹은 &#926 모양으로 표기 되기도 한다. (알파벳 대문자 E 처럼 보이는 그리스 문자 "Xi" 에서 따왔다) 또, 아주 가끔(?) &#9830; 의 모양으로도 표기된다. 예를 들면, 1 ether , 1 ETH , &#926;1, 또는 &#9830;1 이렇게 표시된다. 

[TIP]
====
Use Unicode character +U+039E+ for &#926; and +U+2666+ for &#9830;.
====

이더(Ether)는 더 작은 단위로 세분화 될 수 있다. 그리고 그 단위 중 가장 작은 것은 _wei_ 이다. 1 이더는 백경 (1,000,000,000,000,000,000 | 10^18) _wei_ 이다. 사람들이 종종 화폐 이름으로 "이더리움" 말하는 것을 들어 본 적이 있을 것이다. 하지만, 엄연히 얘기하면 그것은 옳은 표현법이 아니다. 이더리움 시스템 그 자체이고, 이더(_ether_) 가 화폐이다.

The value of ether is always represented internally in Ethereum as an unsigned integer value denominated in wei. When you transact 1 ether, the transaction encodes 1000000000000000000 wei as the value.

Ether’s various denominations have both a scientific name using the International System of Units (SI) and a colloquial name that pays homage to many of the great minds of computing and cryptography.

Ether denominations and unit names shows the various units, their colloquial (common) names, and their SI names. In keeping with the internal representation of value, the table shows all denominations in wei (first row), with ether shown as 1018 wei in the 7th row.

[[ether_denominations]]
.Ether denominations and unit names
[options="header"]
|===
| Value (in wei) | Exponent | Common name | SI name
| 1 | 1 | wei | Wei
| 1,000 | 10^3^ | Babbage | Kilowei or femtoether
| 1,000,000 | 10^6^ | Lovelace | Megawei or picoether
| 1,000,000,000 | 10^9^ | Shannon | Gigawei or nanoether
| 1,000,000,000,000 | 10^12^ | Szabo | Microether or micro
| 1,000,000,000,000,000 | 10^15^ | Finney | Milliether or milli
| _1,000,000,000,000,000,000_ | _10^18^_ | _Ether_ | _Ether_
| 1,000,000,000,000,000,000,000 | 10^21^ | Grand | Kiloether
| 1,000,000,000,000,000,000,000,000 | 10^24^ | | Megaether
|===

[[choosing_eth_wallet]]
=== 이더리움 지갑 고르기

((("Ethereum (generally)","wallet choices")))((("wallets","choosing")))((("wallets","defined"))) 용어 "지갑"은 많은 의미를 가지고 있다. although they are all related and on a day-to-day basis boil down pto pretty much the same thing. 우리는 당신의 이더리움 계정을 관리하는 것을 보조하는 소프트웨어 어플리케이션의 의미로 "지갑"이라는 용어를 사용하려고 한다. 즉, 이더리움 지갑은 이더리움 시스템으로의 gateway 이다. 나의 키를 보유하고 있고 나의 의지에 따라 거래를 생성하고 broadcast 시킨다. 이더리움 지갑의 종류가 많고 각각 다른 특징과 디자인을 가지고 있기 때문에, 선택하는 것이 쉽지는 않다. 몇 개는 입문자에게 알맞고 몇 개는 전문가에게 알맞는다. 이더리움 플랫폼은 그 스스로 여전히 개선되고 있기에 최고의 지갑은 플랫폼 업그레이드에 따라서 같이 변화를 적용시키는 것이라고 할 수 있다. (are often the ones that adapt to the changes)

당신이 특정 지갑을 골랐는데 그 지갑이 작동하는 방식이 마음에 들지 않는다면 &#x2014; 혹은 괜찮았지만 또 다른 것들을 경험해보고 싶었다면 &#x2014 상당히 쉽게 바꿀 수 있기 때문에 그 점에 대해서는 걱정할 필요가 없다.&#x2014 지갑 바꿀때 해야할 것은 2가지이다. 내 돈(fund)을 새 지갑으로 옮기고 private eys를 export 해서 새 지갑에 import 하면 된다. 

이 책에서 우리는 3가지 다른 지갑을 사용해 볼 것이다. 모바일 지갑, 데스크탑 지갑 그리고 웹 기반의 지갑. 이 3가지 지갑은 수많은 다양성(complexity) 와 특징을 대변하기에 이렇게 선택하였다. 그러나, 이것이 지갑의 품질과 보안을 보증하는 것은 아니다. 단지 구현과 테스팅을 하는데 있어서 좋은 시작인 것이다. 

((("private keys","wallets and"))) 지갑 어플리케이션이 작동하기 위해서 기억해야할 것이 있다. 지갑 어플리케이션은 private keys 에 접근할 수 있는 권한이 있기 때문에, wallet application 을 믿을 수 있는 곳에서 다운로드 받고 사용해야한다는 점이다. 다행히도, 보통, 유명한 지갑 어플리케이션일수록 믿을만한 곳이다. Nevertheless, it is good practice to avoid "putting all your eggs in one basket" and have your Ethereum accounts spread across a couple of wallets.

다음 목록은 입문자에게 적절한 지갑들이다 : 

MetaMask:: ((("MetaMask")))MetaMask is a browser extension wallet that runs in your browser (Chrome, Firefox, Opera, or Brave Browser). It is easy to use and convenient for testing, as it is able to connect to a variety of Ethereum nodes and test blockchains. MetaMask is a web-based wallet.

Jaxx:: ((("Jaxx")))((("wallets","Jaxx")))Jaxx is a multiplatform and multicurrency wallet that runs on a variety of operating systems, including Android, iOS, Windows, macOS, and Linux. It is often a good choice for new users as it is designed for simplicity and ease of use. Jaxx is either a mobile or a desktop wallet, depending on where you install it.

MyEtherWallet (MEW):: ((("Ethereum Classic (ETC)","Emerald Wallet and")))((("MyEtherWallet (MEW)")))((("wallets","Emerald Wallet")))((("wallets","MyEtherWallet")))MyEtherWallet is a web-based wallet that runs in any browser. It has multiple sophisticated features we will explore in many of our examples. MyEtherWallet is a web-based wallet.

Emerald Wallet:: ((("Emerald Wallet")))Emerald Wallet is designed to work with the Ethereum Classic blockchain, but is compatible with other Ethereum-based blockchains. It's an open source desktop application and works under Windows, macOS, and Linux. Emerald Wallet can run a full node or connect to a public remote node, working in a "light" mode. It also has a companion tool to do all operations from the command line.

We'll start by installing MetaMask on a desktop&#x2014;but first, we'll briefly discuss controlling and managing keys.

[[control_responsibility]]
=== Control and Responsibility

((("Ethereum (generally)","control and responsibility", id="ix_02intro-asciidoc1", range="startofrange"))) 이더리움과 같은 오픈 블록체인은 탈 중앙화된 시스템으로서 작동하기에 매우 중요하다. That means lots of things, but one crucial aspect is that each user of Ethereum can&#x2014;and should&#x2014;control their own private keys, which are the things that control access to funds and smart contracts. We sometimes call the combination of access to funds and smart contracts an "account" or "wallet." These terms can get quite complex in their functionality, so we will go into this in more detail later. As a fundamental principle, however, it is as easy as one private key equals one "account." Some users choose to give up control over their private keys by using a third-party custodian, such as an online exchange. In this book, we will teach you how to take control and manage your own private keys.
